{{- if .Values.app.efs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-efs
spec:
  {{ if .Values.app.efs.pvc }}
  {{- toYaml .Values.app.efs.pvc | nindent 2  }}
  {{- end }}
{{- end }}